### ISSUE TITLE
Create prettier logging output

### ISSUE THREAD

**Issue by mdeggies** [hashicorp/inclusify#11]
Maybe add in some colors? :)

**Comment by maximevaillancourt** [comment]
Hi Michele! I'm learning Go and would love to help out on this one. Is it okay with you if I assign myself?

(assuming yes, do you have anything in mind specifically, or should I try something and see how it turns out?)

**Comment by mdeggies** [comment]
Hi @maximevaillancourt, happy to have you join in! I don't have anything specific in mind- any improvement over the wall of white INFO text we have now would be awesome.

**Comment by maximevaillancourt** [comment]
Excellent, thank you! I'm currently setting up my environment variables with a test repository of mine. I'll ping you once I have a PR up and ready. 🙂
