### ISSUE TITLE
Exclude go imports from the find/replace in the updateRefs command

### ISSUE THREAD

**Issue by mdeggies** [hashicorp/inclusify#20]
In the `updateRefs` command, we loop through all directories and files in the local clone of the repo. If the directories/files are excluded via the --exclusion flag or the `INCLUSIFY_EXCLUSIONS` env var, they will be skipped. Otherwise, all references to `master` in any file will be replaced with `main`. A recent run found that some go imports have `master` in their name, which this tool tries to replace:

<img width="1641" alt="Screen Shot 2020-10-07 at 2 46 09 PM" src="https://user-images.githubusercontent.com/12939567/95391889-b2acd380-08ac-11eb-8ff9-aee871df82f0.png">

The example above is from this PR: https://github.com/hashicorp/terraform-provider-ad/pull/47/files

This is the file/function that we should modify: https://github.com/hashicorp/inclusify/blob/main/pkg/files/updateRefs.go#L71.

**Comment by HemantJoshi11** [comment]
let me try

**Comment by HemantJoshi11** [comment]
@mdeggies    Please review my changes

**Comment by mdeggies** [comment]
Closing, as this project has been deprecated
