### ISSUE TITLE
README should mention that commands should be run in a clone of the repo

### ISSUE THREAD

**Issue by topfunky** [hashicorp/inclusify#33]
*What I did*

I set the appropriate ENV vars, but I happened to be in a different repo when running `createBranches` and `updateRefs`.

*What happened*

It seemed that the tool started doing searches on the files in my current directory rather than on the repo specified in my env vars.

*What I expected to happen*

Either the README should start with instructions to `git clone` and `cd` to the repo in question, or the app should work exclusively with the repo specified in ENV vars (instead of the current working directory).

**Comment by mdeggies** [comment]
Ah, good catch and thanks for the note. Since this tooling is now largely supported in GitHub itself, `inclusify` has been deprecated.
